version: '2'
services:
  kopf: #2
    image: qnib/kopf:d12
    networks:
     - consul-net
    ports:
     - 80:80
    environment:
     - DC_NAME=swarm
     - ES_CLUSTER_NAME=swarm
     - CONSUL_CLUSTER_IPS=green_consul,blue_consul
    ports:
     - 80:80

networks:
  consul-net:
    driver: overlay
