version: '2'
services:
  consul: #global
    ports:
      - 8500:8500
    networks:
      - consul-net
    environment:
      - DC_NAME=swarm
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_SKIP_CURL=true
    image: qnib/alpn-consul:d12
    volumes:
      - /etc/hostname:/etc/docker-hostname

networks:
  consul-net:
    driver: overlay
