version: '2'
services:
  elasticsearch: #global
    image: qnib/alpn-elasticsearch:2.3.5
    networks:
     - consul-net
    environment:
     - DC_NAME=swarm
     - ES_CLUSTER_NAME=swarm
     - CONSUL_CLUSTER_IPS=green_consul,blue_consul
    ports:
     - 9200:9200
     - 9300:9300
    volumes:
     - /opt/elasticsearch/data/
     - /opt/elasticsearch/logs/

networks:
  consul-net:
    driver: overlay
